server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    types {
        text/html                   html;
        text/css                    css;
        application/javascript      js mjs;
        application/json            json;
    }
}
